name: 00-terraform-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Terraform version
        shell: powershell
        run: |
          terraform -v

      - name: Terraform init
        shell: powershell
        run: |
          Set-Location terraform
          terraform init

      - name: Terraform apply
        shell: powershell
        run: |
          Set-Location terraform
          terraform apply -auto-approve
