name: test-runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Hello test
        run: echo "Runner works!"

      - name: Who am I
        run: whoami

      - name: Check Hyper-V
        run: Get-VM
        shell: powershell
