name: terraform-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Check Terraform version
        shell: powershell
        run: |
          terraform -v

      - name: Terraform init
        shell: powershell
        run: |
          cd terraform
          terraform init

      - name: Terraform apply
        shell: powershell
        run: |
          cd terraform
          terraform apply -auto-approve
